<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
<!-- Include common properties -->
<xacro:include filename="common_properties.xacro"/>
<!-- Call material macros -->
<xacro:material_grey/>
<xacro:material_green/>
<xacro:material_white/>

<!-- Define properties for calculations -->
<xacro:property name="base_length" value="0.6"/>
<xacro:property name="base_width" value="0.4"/>
<xacro:property name="base_height" value="0.2"/>
<xacro:property name="wheel_radius" value="0.1"/>
<xacro:property name="wheel_length" value="0.05"/>
<xacro:property name="caster_radius" value="0.05"/>
<xacro:property name="lidar_radius" value="0.1"/>
<xacro:property name="lidar_length" value="0.05"/>
<xacro:property name="camera_size" value="0.05"/>

<!-- Base footprint -->
<link name="base_footprint"/>

<!-- Base link -->
<link name="base_link">
  <visual>
    <geometry>
      <box size="${base_length} ${base_width} ${base_height}"/>
    </geometry>
    <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
    <material name="green"/>
  </visual>
  <collision>
    <geometry>
      <box size="${base_length} ${base_width} ${base_height}"/>
    </geometry>
    <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
  </collision>
  <inertial>
    <mass value="5.0"/>
    <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
    <inertia ixx="${(5.0/12) * (base_width*base_width + base_height*base_height)}" ixy="0" ixz="0"
             iyy="${(5.0/12) * (base_length*base_length + base_height*base_height)}" iyz="0"
             izz="${(5.0/12) * (base_length*base_length + base_width*base_width)}" />
  </inertial>
</link>

<!-- LiDAR -->
<link name="lidar">
  <visual>
    <geometry>
      <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
    </geometry>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <material name="white"/>
  </visual>
  <collision>
    <geometry>
      <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
    </geometry>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </collision>
  <inertial>
    <mass value="0.5"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <inertia ixx="${(0.5/12) * (3*lidar_radius*lidar_radius + lidar_length*lidar_length)}" ixy="0" ixz="0"
             iyy="${(0.5/12) * (3*lidar_radius*lidar_radius + lidar_length*lidar_length)}" iyz="0"
             izz="${(0.5/2) * (lidar_radius*lidar_radius)}" />
  </inertial>
</link>

<!-- Camera -->
<link name="camera_link">
  <visual>
    <geometry>
      <box size="${camera_size} ${camera_size} ${camera_size}"/>
    </geometry>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <material name="white"/>
  </visual>
  <collision>
    <geometry>
      <box size="${camera_size} ${camera_size} ${camera_size}"/>
    </geometry>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </collision>
  <inertial>
    <mass value="0.3"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <inertia ixx="${(0.3/12) * (camera_size*camera_size + camera_size*camera_size)}" ixy="0" ixz="0"
             iyy="${(0.3/12) * (camera_size*camera_size + camera_size*camera_size)}" iyz="0"
             izz="${(0.3/12) * (camera_size*camera_size + camera_size*camera_size)}" />
  </inertial>
</link>

<!-- Left Wheel -->
<link name="left_wheel">
  <visual>
    <geometry>
      <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
    </geometry>
    <origin xyz="0 0 0" rpy="1.57 0 0"/>
    <material name="grey"/>
  </visual>
  <collision>
    <geometry>
      <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
    </geometry>
    <origin xyz="0 0 0" rpy="1.57 0 0"/>
  </collision>
  <inertial>
    <mass value="1.0"/>
    <origin xyz="0 0 0" rpy="1.57 0 0"/>
    <inertia ixx="${(1.0/12) * (3*wheel_radius*wheel_radius + wheel_length*wheel_length)}" ixy="0" ixz="0"
             iyy="${(1.0/12) * (3*wheel_radius*wheel_radius + wheel_length*wheel_length)}" iyz="0"
             izz="${(1.0/2) * (wheel_radius*wheel_radius)}" />
  </inertial>
</link>

<!-- Right Wheel -->
<link name="right_wheel">
  <visual>
    <geometry>
      <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
    </geometry>
    <origin xyz="0 0 0" rpy="1.57 0 0"/>
    <material name="grey"/>
  </visual>
  <collision>
    <geometry>
      <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
    </geometry>
    <origin xyz="0 0 0" rpy="1.57 0 0"/>
  </collision>
  <inertial>
    <mass value="1.0"/>
    <origin xyz="0 0 0" rpy="1.57 0 0"/>
    <inertia ixx="${(1.0/12) * (3*wheel_radius*wheel_radius + wheel_length*wheel_length)}" ixy="0" ixz="0"
             iyy="${(1.0/12) * (3*wheel_radius*wheel_radius + wheel_length*wheel_length)}" iyz="0"
             izz="${(1.0/2) * (wheel_radius*wheel_radius)}" />
  </inertial>
</link>

<!-- Caster -->
<link name="caster_wheel">
  <visual>
    <geometry>
      <sphere radius="${caster_radius}"/>
    </geometry>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <material name="grey"/>
  </visual>
  <collision>
    <geometry>
      <sphere radius="${caster_radius}"/>
    </geometry>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </collision>
  <inertial>
    <mass value="0.2"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <inertia ixx="${(2.0/5) * 0.2 * caster_radius * caster_radius}" ixy="0" ixz="0"
             iyy="${(2.0/5) * 0.2 * caster_radius * caster_radius}" iyz="0"
             izz="${(2.0/5) * 0.2 * caster_radius * caster_radius}" />
  </inertial>
</link>

<!-- Joints -->
<joint name="base_joint" type="fixed">
  <parent link="base_footprint"/>
  <child link="base_link"/>
  <origin xyz="0 0 0.1" rpy="0 0 0"/>
</joint>

<joint name="base_left_wheel_joint" type="continuous">
  <parent link="base_link"/>
  <child link="left_wheel"/>
  <origin xyz="-0.15 0.225 0" rpy="0 0 0"/>
  <axis xyz="0 1 0"/>
</joint>

<joint name="base_right_wheel_joint" type="continuous">
  <parent link="base_link"/>
  <child link="right_wheel"/>
  <origin xyz="-0.15 -0.225 0" rpy="0 0 0"/>
  <axis xyz="0 1 0"/>
</joint>

<joint name="base_caster_wheel_joint" type="fixed">
  <parent link="base_link"/>
  <child link="caster_wheel"/>
  <origin xyz="0.20 0 -0.05" rpy="0 0 0"/>
</joint>

<joint name="base_lidar_joint" type="fixed">
  <parent link="base_link"/>
  <child link="lidar"/>
  <origin xyz="0 0 0.225" rpy="0 0 0"/>
</joint>

<joint name="base_camera_joint" type="fixed">
  <parent link="base_link"/>
  <child link="camera_link"/>
  <origin xyz="0 0 0.3" rpy="0 0 0"/>
</joint>
</robot>